"""empty message

Revision ID: 45a4a470f43e
Revises: None
Create Date: 2016-08-28 15:16:04.804259

"""

# revision identifiers, used by Alembic.
revision = '45a4a470f43e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_name', sa.String(), nullable=True),
    sa.Column('geocoded_name', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('checkout_datetime', sa.DateTime(), nullable=True),
    sa.Column('checkout_kiosk_id', sa.Integer(), nullable=True),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('return_kiosk_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkout_kiosk_id'], ['kiosk.id'], ),
    sa.ForeignKeyConstraint(['return_kiosk_id'], ['kiosk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('rider')
    op.drop_table('kiosk')
    ### end Alembic commands ###
