"""empty message

Revision ID: 480293734eb3
Revises: eae1467ea534
Create Date: 2016-08-28 16:09:33.088678

"""

# revision identifiers, used by Alembic.
revision = '480293734eb3'
down_revision = 'eae1467ea534'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('checkout_kiosk_id', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('return_kiosk_id', sa.Integer(), nullable=True))
    op.drop_constraint('trip_checkout_kiosk_fkey', 'trip', type_='foreignkey')
    op.drop_constraint('trip_return_kiosk_fkey', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'kiosk', ['checkout_kiosk_id'], ['id'])
    op.create_foreign_key(None, 'trip', 'kiosk', ['return_kiosk_id'], ['id'])
    op.drop_column('trip', 'checkout_kiosk')
    op.drop_column('trip', 'return_kiosk')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('return_kiosk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('checkout_kiosk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_return_kiosk_fkey', 'trip', 'kiosk', ['return_kiosk'], ['id'])
    op.create_foreign_key('trip_checkout_kiosk_fkey', 'trip', 'kiosk', ['checkout_kiosk'], ['id'])
    op.drop_column('trip', 'return_kiosk_id')
    op.drop_column('trip', 'checkout_kiosk_id')
    ### end Alembic commands ###
