"""empty message

Revision ID: 65cef41eae0c
Revises: None
Create Date: 2016-08-25 19:38:21.266104

"""

# revision identifiers, used by Alembic.
revision = '65cef41eae0c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('checkout_datetime', sa.DateTime(), nullable=True),
    sa.Column('checkout_kiosk', sa.String(), nullable=True),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('return_kiosk', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('trip')
    ### end Alembic commands ###
