"""empty message

Revision ID: 7dde3cfde867
Revises: 2f33c933fc3a
Create Date: 2016-10-14 22:04:18.907684

"""

# revision identifiers, used by Alembic.
revision = '7dde3cfde867'
down_revision = '2f33c933fc3a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinate')
    op.add_column('route', sa.Column('route', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'route')
    op.create_table('coordinate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('lng', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='coordinate_route_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coordinate_pkey')
    )
    ### end Alembic commands ###
