"""empty message

Revision ID: 89383a79eb6c
Revises: 1c36fd664663
Create Date: 2016-10-10 19:37:16.014146

"""

# revision identifiers, used by Alembic.
revision = '89383a79eb6c'
down_revision = '1c36fd664663'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('kiosk_one_id', sa.Integer(), nullable=True))
    op.add_column('route', sa.Column('kiosk_two_id', sa.Integer(), nullable=True))
    op.drop_constraint('route_return_kiosk_id_fkey', 'route', type_='foreignkey')
    op.drop_constraint('route_checkout_kiosk_id_fkey', 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'kiosk', ['kiosk_two_id'], ['id'])
    op.create_foreign_key(None, 'route', 'kiosk', ['kiosk_one_id'], ['id'])
    op.drop_column('route', 'return_kiosk_id')
    op.drop_column('route', 'checkout_kiosk_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('checkout_kiosk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('return_kiosk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key('route_checkout_kiosk_id_fkey', 'route', 'kiosk', ['checkout_kiosk_id'], ['id'])
    op.create_foreign_key('route_return_kiosk_id_fkey', 'route', 'kiosk', ['return_kiosk_id'], ['id'])
    op.drop_column('route', 'kiosk_two_id')
    op.drop_column('route', 'kiosk_one_id')
    ### end Alembic commands ###
