"""empty message

Revision ID: 95d1a44def2a
Revises: 7dde3cfde867
Create Date: 2016-10-14 22:05:48.942634

"""

# revision identifiers, used by Alembic.
revision = '95d1a44def2a'
down_revision = '7dde3cfde867'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('coordinates', postgresql.JSON(), nullable=True))
    op.drop_column('route', 'route')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('route', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('route', 'coordinates')
    ### end Alembic commands ###
