"""empty message

Revision ID: eae1467ea534
Revises: 45a4a470f43e
Create Date: 2016-08-28 15:55:31.590932

"""

# revision identifiers, used by Alembic.
revision = 'eae1467ea534'
down_revision = '45a4a470f43e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('checkout_kiosk', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('return_kiosk', sa.Integer(), nullable=True))
    op.drop_constraint('trip_checkout_kiosk_id_fkey', 'trip', type_='foreignkey')
    op.drop_constraint('trip_return_kiosk_id_fkey', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'kiosk', ['return_kiosk'], ['id'])
    op.create_foreign_key(None, 'trip', 'kiosk', ['checkout_kiosk'], ['id'])
    op.drop_column('trip', 'checkout_kiosk_id')
    op.drop_column('trip', 'return_kiosk_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('return_kiosk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('checkout_kiosk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_return_kiosk_id_fkey', 'trip', 'kiosk', ['return_kiosk_id'], ['id'])
    op.create_foreign_key('trip_checkout_kiosk_id_fkey', 'trip', 'kiosk', ['checkout_kiosk_id'], ['id'])
    op.drop_column('trip', 'return_kiosk')
    op.drop_column('trip', 'checkout_kiosk')
    ### end Alembic commands ###
