"""empty message

Revision ID: fe394ab5c573
Revises: 95d1a44def2a
Create Date: 2016-11-13 20:19:13.366044

"""

# revision identifiers, used by Alembic.
revision = 'fe394ab5c573'
down_revision = '95d1a44def2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('one_to_two_count', sa.Integer(), nullable=True))
    op.add_column('route', sa.Column('two_to_one_count', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'route', ['route_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'route_id')
    op.drop_column('route', 'two_to_one_count')
    op.drop_column('route', 'one_to_two_count')
    ### end Alembic commands ###
