"""empty message

Revision ID: feede7174a42
Revises: fe394ab5c573
Create Date: 2016-11-13 20:37:00.045410

"""

# revision identifiers, used by Alembic.
revision = 'feede7174a42'
down_revision = 'fe394ab5c573'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'two_to_one_count')
    op.drop_column('route', 'one_to_two_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('one_to_two_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('two_to_one_count', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
